#!/bin/sh

# Trace function entry/exit from supplied <function-name>

dtrace='
pid$1:cmd-key-happy:$2:entry
{
    self->trace = 1;
}

pid$1:cmd-key-happy:$2:return
/self->trace/
{
    self->trace = 0;
}

pid$1:cmd-key-happy::entry,
pid$1:cmd-key-happy::return
/self->trace/
{
}
'

/usr/sbin/dtrace -F -n "$dtrace" -o /dev/stderr `pgrep cmd-key-happy` $1
