#!/bin/sh

# Measure event handling latency.

dtrace='

dtrace:::BEGIN
{
  printf("Tracing PID %d... Ctrl-C to end.\n", $target);
}

pid$target::*EventTap*handleEvent*:entry
{
  self->start = timestamp;
}

pid$target::*EventTap*handleEvent*:return
/self->start/
{
  @time = quantize((timestamp - self->start) / 1000);
  self->start = 0;
}

dtrace:::END
{
  printf("cmd-key-happy: event handling latency (microseconds)");
  printa(@time);
}
'

/usr/sbin/dtrace -q -n "$dtrace" -o /dev/stderr -p `pgrep cmd-key-happy`
